export const LIST_ALL_PRODUCTS = 'LIST_ALL_PRODUCTS';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const LIST_CATEGORIES = 'LIST_CATEGORIES';
export const LIST_CURRENCIES = 'LIST_CURRENCIES';